---

- name: Include directories tasks
  ansible.builtin.include_tasks: ensure_directories.yml

- name: Include configure node tasks
  ansible.builtin.include_tasks: ensure_configure_node.yml
  when:
    - (k3s_control_node and k3s_controller_list | length == 1)
      or (k3s_primary_control_node and k3s_controller_list | length > 1)
    - not ansible_check_mode

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Include configure node tasks
  ansible.builtin.include_tasks: ensure_configure_node.yml
  when: k3s_build_cluster

- name: Determine if the systems are already clustered
  ansible.builtin.stat:
    path: "{{ k3s_token_location }}"
  register: k3s_token_cluster_check

- name: Include control plane started tasks
  ansible.builtin.include_tasks: ensure_started.yml
  when: (k3s_control_node and k3s_controller_list | length == 1)
        or (k3s_primary_control_node and k3s_controller_list | length > 1)
        or k3s_token_cluster_check.stat.exists
