---
- name: Ensure {{ directory.name }} exists
  ansible.builtin.file:
    path: "{{ directory.path }}"
    state: directory
    mode: "{{ directory.mode | default(755) }}"
  become: "{{ k3s_become }}"
  loop: "{{ k3s_ensure_directories_exist }}"
  loop_control:
    loop_var: directory
  when:
    - directory.path is defined
    - directory.path | length > 0
    - directory.path != omit
