---

- name: Import drain and remove nodes tasks
  ansible.builtin.import_tasks: ensure_drain_and_remove_nodes.yml

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Import configure manifests tasks
  ansible.builtin.import_tasks: ensure_configure_manifests.yml
  when: k3s_primary_control_node

- name: Import configure additional tasks
  ansible.builtin.import_tasks: ensure_configure_additional.yml

- name: Import install tasks
  ansible.builtin.import_tasks: ensure_installed.yml

- name: Include check cluster tasks
  ansible.builtin.include_tasks: post_checks/check_cluster.yml
  when:
    - k3s_control_delegate is defined
    - k3s_control_delegate == inventory_hostname

- name: Import configure cluster tasks
  ansible.builtin.import_tasks: ensure_configure_cluster.yml
  when:
    - k3s_build_cluster is defined
    - k3s_build_cluster
    - k3s_registration_address is defined
